apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: creative-studio-parent
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/DenisRuparel/Timoni-implementation---DevOps
    targetRevision: main
    path: argocd/apps
  destination:
    server: https://192.168.56.107:6443
    namespace: argocd
  syncPolicy:
    automated:
      prune: true   
      selfHeal: true
