apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: creative-studio-prod
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/DenisRuparel/Timoni-implementation---DevOps
    targetRevision: main
    path: deploy/manifests/prod
  destination:
    server: https://192.168.56.107:6443
    namespace: creative-studio-prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
